version: '3'
services:
  bot:
    container_name: bot
    image: bot_image
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: db
    image: db_image
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    command: |
      postgres
      -c wal_level=replica
      -c hot_standby=on
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c hot_standby_feedback=on
      -c log_replication_commands=on
  db_repl:  
    image: db_repl_image
    container_name: db_repl
    env_file:
      - .env
    environment:
      PGUSER: ${DB_REPL_USER}
      PGPASSWORD: ${DB_PASSWORD}
    depends_on:
      - db