CREATE USER DB_USER WITH REPLICATION ENCRYPTED PASSWORD 'DB_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE DB_DATABASE TO DB_USER;

CREATE USER DB_REPL_USER WITH REPLICATION ENCRYPTED PASSWORD 'DB_REPL_PASSWORD';

CREATE DATABASE DB_DATABASE;

\connect DB_DATABASE;

CREATE TABLE IF NOT EXISTS emails(id SERIAL PRIMARY KEY, email VARCHAR(70) NOT NULL);
CREATE TABLE IF NOT EXISTS phones(id SERIAL PRIMARY KEY, phone VARCHAR(70) NOT NULL);